### ISSUE TITLE
Frame rate

### ISSUE THREAD

**Issue by RyanAMTB** [kWAYTV/dma-cheat-base#5]
Hello, what frame rate does the GUI render at? If it's not 120, is it possible to change without rewriting the entire repo? 

Thanks for reading.

**Comment by kWAYTV** [comment]
> Hello, what frame rate does the GUI render at? If it's not 120, is it possible to change without rewriting the entire repo?
> 
> Thanks for reading.

https://github.com/kWAYTV/dma-cheat-base/blob/main/project-d/Source/Overlay/Overlay.cpp#L61
